### ISSUE TITLE
Multiseat support for swayidle

### ISSUE THREAD

**Issue by emersion** [swaywm/swayidle#1]
`swayidle` only supports one seat.

**Comment by qguv** [comment]
If I understand it correctly, after #77, swayidle supports _any_ one named seat. But the restriction of one seat at a time, set at launch, remains.

**Comment by emersion** [comment]
Right. I'd say requiring one swayidle instance per seat is reasonable.

**Comment by qguv** [comment]
Hm, what does it mean then to have one swayidle instance per seat? Does this mean any seat-user can lock the device such that only the same seat-user can unlock it later? If so, I can think of a few issues…

An example: I'm imagining a pair-programming setup where two users are sitting at the same desktop, each using different keyboards and keyboard layouts. If user A leaves for dinner and user B continues working, user B will soon be locked out of the session due to user A's timer. If user B can't type in user A's keyboard layout, or doesn't have physical access to the seat for whatever reason, then user B will be locked out for good.

Since the _password_ is the information required to unlock the device, my intuition says that, by default, _any_ seat should be able to input that information.

If separate instances are desirable for some other reason, there would at least need to be a way for the instances to communicate with each other to avoid this sort of thing.

Just some ideas :slightly_smiling_face:

**Comment by emersion** [comment]
Locking from one seat doesn't prevent other seats from unlocking.

**Comment by qguv** [comment]
Ah, in that case, #77 closes this issue!

**Comment by Lassebq** [comment]
If you have multiple seats at the same time and both of them have swayidle running, despite you being active on one seat, swayidle will still trigger suspend on another seat. So I'm not sure if there's a proper multiseat support?

**Comment by emersion** [comment]
Each seat has independent idle state, yes. This is by design.

**Comment by Lassebq** [comment]
Either it's flawed by design or it shouldn't tick when seat is inactive.
