### ISSUE TITLE
Freeze after kernel update

### ISSUE THREAD

**Issue by ignamartinoli** [swaywm/swayidle#124]
I just updated to the latest kernel version `5.18.0`.
When I close my laptop lid, reopen it and unlock `swaylock`, the screen remains black with only the cursor visible. Sometimes when reopening the lid, even `swaylock` would not be visible and after typing my password on screen I would see the cursor in the black screen.
This is my idle configuration:
```i3
exec swayidle -w \
	timeout 600 'swaylock -c 000000' \
	timeout 900 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"' \
	before-sleep 'swaylock -c 000000'
```

**Comment by ignamartinoli** [comment]
After updating Gentoo to kernel `1.18.1-r1` I can confirm this is a bug on `swayidle` side.
If I disable `swayidle`, after closing and opening the lid everything works fine.
If I have `swayidle` enabled with the options mentioned in the previous comment, after reopening the lid I am greeted by `swaylock`, but it flickers and behaves unresponsive

**Comment by raiguard** [comment]
I can confirm this issue, it's maddening. Seemingly randomly, instead of shutting off my monitors, swayidle will just blank them out. No mouse cursor, no keyboard control, nothing. The monitors are on, but are just displaying black. I can't escape to a TTY or do absolutely anything, so I have to restart my PC entirely, losing my work.

I attempted to pull up journalctl from before the restart, but it didn't keep the record. I haven't found a way to consistently trigger the issue yet.

**Comment by ignamartinoli** [comment]
Actually, if you disable `swayidle`, at least on latest kernel, the problem persist. [This](https://imgur.com/a/QFALIQ0) is an example running `cmatrix`
