### ISSUE TITLE
When playing a video in a web browser the screen locks

### ISSUE THREAD

**Issue by hramrach** [swaywm/swayidle#173]
This is not seen under X11

**Comment by hramrach** [comment]
This is #104, still not resolved

**Comment by kennylevinsen** [comment]
swayidle does not determine when something is idle, it only reacts to sway saying that the system has been idle for longer than the requested idle timeout.

If the screen locks while playing a video, it is most likely a case of the client (the browser) not using Wayland idle inhibition protocol correctly so that sway does not know to not trigger idle events.

**Comment by kennylevinsen** [comment]
(While I closed the issue as it is not a swayidle problem, feel free to be more specific about which browser and version.)

**Comment by hramrach** [comment]
Chromium, any version, as described in #104

**Comment by kennylevinsen** [comment]
Works fine with chromium here. The browser needs to be run in Wayland mode though: `--ozone-platform=wayland --enable-features=UseOzonePlatform`. You can usually put that in a ~/.config/chromium-flags.conf` or something, depending on the wrapper script provided by your distro.

**Comment by hramrach** [comment]
The current option is `--ozone-platform-hint=auto`, with that it seems to work, thanks.
