### ISSUE TITLE
swayidle ignores controller input

### ISSUE THREAD

**Issue by clarfon** [swaywm/swayidle#5]
sway commit: gfa2d2c85
wlroots commit: 8beeb883

Controller is a GameCube controller via a USB adapter, which works as expected in most games. The issue is that swayidle doesn't seem to be interpreting the controller input as any actual input and triggers even if I've been playing for a few minutes. I suspect that this hasn't been coded into swayidle at all, but if it has and this is an issue for my specific config, I'd be more than willing to provide more info.

**Comment by ainola** [comment]
@clarfon Dolphin's idle inhibit has pretty much never worked for me. I can confirm that the latest version in Arch also does not inhibit idle on KDE/X11. So I think it's safe to say the bug lies in Dolphin.

However, I think it might be interesting to get idle inhibit for X11 games. For instance, Stardew Valley inhibits under X11 but not under Sway/Xwayland.

**Comment by ddevault** [comment]
Unrelated: you reminded me that this isn't really our bug.

**Comment by ainola** [comment]
Should I file a new bug wrt swayidle respecting xwayland idle suspension or is this also beyond scope?

**Comment by emersion** [comment]
>swayidle respecting xwayland idle suspension

From what I've understood this isn't possible.

**Comment by ddevault** [comment]
You might want to open a ticket with Xwayland instead.
